// KA1835VG6 (MK92 docking station controller) module
// only embedded ROM switching implemented

// 2024 (c) Bs0Dd

var M92_STAT;
var M92_CMD;
var M92_AVAL;

function DockInit() {
    M92_STAT = 0;
    M92_CMD = 0;
    M92_AVAL = 0b0000000010000000; // 4th 588VA1 (read mode)
                                   // CS generated by CS111 out from MK90's VG4 (RD/WR at 0xE81E)
                                   // Only AD 15, 14, 7, 1 connected
                                   // AD 15, 14, 1 - grounded (state 0)
                                   // AD 7 - 5V power? (state 1)
}

function DockStatWr(val) {
    M92_STAT = val & 0xFFFF;
    //console.log("VG6 status write:", val.toString(2))
}

function DockCmdWr(val) {
    M92_CMD = val & 0xFFFF;
    //console.log("VG6 command write:", val.toString(2))
}

function DockAvalRd() {
    return M92_AVAL;
}

function DockStatRd() {
    return M92_STAT;
}

function DockCmdRd() {
    return M92_CMD;
}
